libmatrix: Include missing <utility> header
Fixes build with gcc12
| ../git/src/libmatrix/program.h:43:21: error: 'exchange' is not a member of 'std'                                                   |    43 |         ready_(std::exchange(shader.ready_, false)),                                                                       |       |                     ^~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>