Fix literal suffit error with C++11
With a recent g++, compilation of src/native-state-x11.cpp will fail
with the following error:

../src/native-state-x11.cpp:63:33: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]

Add the missing space to make it go through.