Do not use deprecated std::auto_ptr
auto_ptr has been deprecated in recent C++ revisions. As glmark2 is
compiled with -Werror by default, this results in compilation failures
with recent g++ versions, e.g:

../src/model.cpp:684:16: error: ‘template<class> class std::auto_ptr’ is deprecated [-Werror=deprecated-declarations]

Replace the use of auto_ptr with unique_ptr throughout the code to fix
this.